org: mehdiahmed
app: my-aws-python-rest-api-app
service: service-test

frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
